add misisng new function

diff --git a/ffmuc-mesh-vpn-wireguard-vxlan/files/lib/gluon/gluon-mesh-wireguard-vxlan/checkuplink b/ffmuc-mesh-vpn-wireguard-vxlan/files/lib/gluon/gluon-mesh-wireguard-vxlan/checkuplink
--- a/ffmuc-mesh-vpn-wireguard-vxlan/files/lib/gluon/gluon-mesh-wireguard-vxlan/checkuplink
+++ b/ffmuc-mesh-vpn-wireguard-vxlan/files/lib/gluon/gluon-mesh-wireguard-vxlan/checkuplink
@@ -12,8 +12,8 @@ else
 	exit
 fi
 
-source functions.sh
-
+source /lib/gluon/gluon-mesh-wireguard-vxlan/functions.sh
+init_vars
 
 
 mesh_vpn_enabled="$(uci get wireguard.mesh_vpn.enabled)"
@@ -45,17 +45,7 @@ CONNECTED=0
 MESH_VPN_IFACE=$(get_site_string mesh_vpn.wireguard.iface)
 
 # Check connectivity to supernode
-
-if wget "http://[$(wg  | grep fe80 | awk '{split($3,A,"/")};{print A[1]}')%$MESH_VPN_IFACE]/"  --timeout=5 -O/dev/null -q
-then
-	GWMAC=$(batctl gwl | awk '/[*]/{print $2}')
-	if batctl ping -c 5 "$GWMAC" > /dev/null 2>&1
-	then
-		CONNECTED=1
-	fi
-fi
-
-if [[ "$CONNECTED" == 1 ]]; then
+if is_connected; then
 	# We have a connection, we are done
 	exit 0
 fi
@@ -161,3 +151,11 @@ ip link set up dev mesh-vpn
 sleep 5
 # If we have a BATMAN_V env we need to correct the throughput value now
 batctl hardif mesh-vpn throughput_override 1000mbit;
+
+# Check again if connected
+if ! is_connected; then
+	logger -p err -t checkuplink "Failed to connect to $PEER_HOST($PEER_ENDPOINT) - Please check your router firewall settings"
+	exit 4
+fi
+
+logger -p info -t checkuplink "Successfully connected to $PEER_HOST($PEER_ENDPOINT)"
